name: Raffle

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v14.1

      - name: "Run stargazers raffle ﱬ"
        run: nix-shell --run "scala-cli package . -o raffle -f && ./raffle gvolpe dconf2nix"
